extends Node

const ITEM_PATH = "res://assets/textures/upgrades/items/"
const UPGRADES = {
	"food": {
		"icon": ITEM_PATH + "food.png",
		"title": "Food",
		"details": "Heals you for 20 health",
		"level": "",
		"requires": [],
		"type": "item",
	},
	"ring1": {
		"icon": ITEM_PATH + "ring.png",
		"title": "Ring",
		"details": "Your spells now spawn 1 more additional attack",
		"level": "Level: 1",
		"requires": [],
		"type": "upgrade",
	},
	"ring2": {
		"icon": ITEM_PATH + "ring.png",
		"title": "Ring",
		"details": "Your spells now spawn an additional attack",
		"level": "Level: 2",
		"requires": ["ring1"],
		"type": "upgrade",
	},
	"armor1": {
		"icon": ITEM_PATH + "helmet.png",
		"title": "Armor",
		"details": "Reduces Damage by 1 point",
		"level": "Level: 1",
		"requires": [],
		"type": "upgrade"
	},
	"armor2": {
		"icon": ITEM_PATH + "helmet.png",
		"title": "Armor",
		"details": "Reduces Damage by an additional 1 point",
		"level": "Level: 2",
		"requires": ["armor1"],
		"type": "upgrade"
	},
	"armor3": {
		"icon": ITEM_PATH + "helmet.png",
		"title": "Armor",
		"details": "Reduces Damage by an additional 1 point",
		"level": "Level: 3",
		"requires": ["armor2"],
		"type": "upgrade"
	},
	"armor4": {
		"icon": ITEM_PATH + "helmet.png",
		"title": "Armor",
		"details": "Reduces Damage by an additional 1 point",
		"level": "Level: 4",
		"requires": ["armor3"],
		"type": "upgrade",
	},
	"speed1": {
		"icon": ITEM_PATH + "boots.png",
		"title": "Speed",
		"details": "Movement Speed Increased by 50% of base speed",
		"level": "Level: 1",
		"requires": [],
		"type": "upgrade",
	},
	"speed2": {
		"icon": ITEM_PATH + "boots.png",
		"title": "Speed",
		"details": "Movement Speed Increased by an additional 50% of base speed",
		"level": "Level: 2",
		"requires": ["speed1"],
		"type": "upgrade",
	},
	"speed3": {
		"icon": ITEM_PATH + "boots.png",
		"title": "Speed",
		"details": "Movement Speed Increased by an additional 50% of base speed",
		"level": "Level: 3",
		"requires": ["speed2"],
		"type": "upgrade",
	},
	"speed4": {
		"icon": ITEM_PATH + "boots.png",
		"title": "Speed",
		"details": "Movement Speed Increased an additional 50% of base speed",
		"level": "Level: 4",
		"requires": ["speed3"],
		"type": "upgrade",
	},
	"tome1": {
		"icon": ITEM_PATH + "tome.png",
		"title": "Tome",
		"details": "Increases the size of spells an additional 10% of their base size",
		"level": "Level: 1",
		"requires": [],
		"type": "upgrade",
	},
	"tome2": {
		"icon": ITEM_PATH + "tome.png",
		"title": "Tome",
		"details": "Increases the size of spells an additional 10% of their base size",
		"level": "Level: 2",
		"requires": ["tome1"],
		"type": "upgrade",
	},
	"tome3": {
		"icon": ITEM_PATH + "tome.png",
		"title": "Tome",
		"details": "Increases the size of spells an additional 10% of their base size",
		"level": "Level: 3",
		"requires": ["tome2"],
		"type": "upgrade",
	},
	"tome4": {
		"icon": ITEM_PATH + "tome.png",
		"title": "Tome",
		"details": "Increases the size of spells an additional 10% of their base size",
		"level": "Level: 4",
		"requires": ["tome3"],
		"type": "upgrade",
	},
	"scroll1": {
		"icon": ITEM_PATH + "scroll.png",
		"title": "Scroll",
		"details": "Decreases of the cooldown of spells by an additional 5% of their base time",
		"level": "Level: 1",
		"requires": [],
		"type": "upgrade",
	},
	"scroll2": {
		"icon": ITEM_PATH + "scroll.png",
		"title": "Scroll",
		"details": "Decreases of the cooldown of spells by an additional 5% of their base time",
		"level": "Level: 2",
		"requires": ["scroll1"],
		"type": "upgrade",
	},
	"scroll3": {
		"icon": ITEM_PATH + "scroll.png",
		"title": "Scroll",
		"details": "Decreases of the cooldown of spells by an additional 5% of their base time",
		"level": "Level: 3",
		"requires": ["scroll2"],
		"type": "upgrade",
	},
	"scroll4": {
		"icon": ITEM_PATH + "scroll.png",
		"title": "Scroll",
		"details": "Decreases of the cooldown of spells by an additional 5% of their base time",
		"level": "Level: 4",
		"requires": ["scroll3"],
		"type": "upgrade",
	},
}
